select distinct on ("seller_products"."id") "seller_products".* from "seller_products" inner join ("products" inner join "category_product" on "category_product"."product_id" = "products"."id" and "category_product"."category_id" = ? inner join "categories" on "category_product"."category_id" = "categories"."id" or "category_product"."category_id" = "categories"."parent_id") on "products"."id" = "seller_products"."product_id" and "products"."status" = ? where "seller_products"."status" = ? and ("seller_products"."user_id" = ? and exists (select * from "products" where "seller_products"."product_id" = "products"."id" and "products"."status" = ?) and "seller_products"."status" = ? or exists (select * from "users" where "seller_products"."user_id" = "users"."id" and (exists (select * from "seller_accounts" where "users"."id" = "seller_accounts"."user_id" and ("holiday_mode" = ? or "holiday_date" != ? or ("holiday_date_start" > ? and "holiday_date_end" < ? or "holiday_date_start" > ? or "holiday_date_end" < ?))) and exists (select * from "seller_subcriptions" where "users"."id" = "seller_subcriptions"."seller_id" and "expiry_date" > ? and exists (select * from "users" where "seller_subcriptions"."seller_id" = "users"."id" and exists (select * from "seller_accounts" where "users"."id" = "seller_accounts"."user_id" and "seller_commission_id" = ?))) and "is_active" = ? or exists (select * from "seller_accounts" where "users"."id" = "seller_accounts"."user_id" and ("seller_commission_id" != ? and "holiday_mode" = ? or "holiday_date" != ? or ("holiday_date_start" > ? and "holiday_date_end" < ? or "holiday_date_start" > ? or "holiday_date_end" < ?))) and "is_active" = ?)) and "seller_products"."status" = ?) order by "seller_products"."id" desc

{
  "products": "select distinct on (\"seller_products\".\"id\") \"seller_products\".* from \"seller_products\" inner join (\"products\" inner join \"category_product\" on \"category_product\".\"product_id\" = \"products\".\"id\" and \"category_product\".\"category_id\" = ? inner join \"categories\" on \"category_product\".\"category_id\" = \"categories\".\"id\" or \"category_product\".\"category_id\" = \"categories\".\"parent_id\") on \"products\".\"id\" = \"seller_products\".\"product_id\" and \"products\".\"status\" = ? where \"seller_products\".\"status\" = ? and (\"seller_products\".\"user_id\" = ? and exists (select * from \"products\" where \"seller_products\".\"product_id\" = \"products\".\"id\" and \"products\".\"status\" = ?) and \"seller_products\".\"status\" = ? or exists (select * from \"users\" where \"seller_products\".\"user_id\" = \"users\".\"id\" and (exists (select * from \"seller_accounts\" where \"users\".\"id\" = \"seller_accounts\".\"user_id\" and (\"holiday_mode\" = ? or \"holiday_date\" != ? or (\"holiday_date_start\" > ? and \"holiday_date_end\" < ? or \"holiday_date_start\" > ? or \"holiday_date_end\" < ?))) and exists (select * from \"seller_subcriptions\" where \"users\".\"id\" = \"seller_subcriptions\".\"seller_id\" and \"expiry_date\" > ? and exists (select * from \"users\" where \"seller_subcriptions\".\"seller_id\" = \"users\".\"id\" and exists (select * from \"seller_accounts\" where \"users\".\"id\" = \"seller_accounts\".\"user_id\" and \"seller_commission_id\" = ?))) and \"is_active\" = ? or exists (select * from \"seller_accounts\" where \"users\".\"id\" = \"seller_accounts\".\"user_id\" and (\"seller_commission_id\" != ? and \"holiday_mode\" = ? or \"holiday_date\" != ? or (\"holiday_date_start\" > ? and \"holiday_date_end\" < ? or \"holiday_date_start\" > ? or \"holiday_date_end\" < ?))) and \"is_active\" = ?)) and \"seller_products\".\"status\" = ?) order by \"seller_products\".\"id\" desc",
  "category_id": "21",
  "item": "category",
  "sort_by": "low_to_high",
  "paginate": "9"
}
